### ISSUE TITLE
How print memory management?

### ISSUE THREAD

**Issue by Shuimo03** [nikofil/rust-os#3]
for example, print process address? or print Page table？

**Comment by h4sh5** [comment]
Can you elaborate on what you mean? If you just want to print out variables, you can use rust's `println!("{:#?}", varirable)` to print out an entire data structure

for example, the page table information is printed out around https://github.com/nikofil/rust-os/blob/master/kernel/src/lib.rs#L87

you can add your own print statements around there.

**Comment by Shuimo03** [comment]
tank you i get the question solution
